-- Vídeos IA generados el 21-sep-2026 (19 × 7,5 créditos) para porras abiertas sin vídeo.
-- Se enlazan solo si la porra sigue abierta y aún no tiene vídeo.
update porras set media_url = 'https://uarnpxjdccbidgzhhavc.supabase.co/storage/v1/object/public/porra-media/agent/quien-ganara-la-final-de-gran-hermano-d.mp4', media_kind = 'video' where id = 'a765d73b-97c9-434e-acf2-a1dcc6854622' and status = 'open' and media_url is null;
update porras set media_url = 'https://uarnpxjdccbidgzhhavc.supabase.co/storage/v1/object/public/porra-media/agent/quien-ganara-el-combate-entre-westcol-y.mp4', media_kind = 'video' where id = '76fd6765-dd70-4b6f-8f5c-e31c52b83354' and status = 'open' and media_url is null;
update porras set media_url = 'https://uarnpxjdccbidgzhhavc.supabase.co/storage/v1/object/public/porra-media/agent/ganara-el-fc-barcelona-al-racing-en-la.mp4', media_kind = 'video' where id = '503da7c8-b7cf-484e-9dcc-a2dddbbea511' and status = 'open' and media_url is null;
update porras set media_url = 'https://uarnpxjdccbidgzhhavc.supabase.co/storage/v1/object/public/porra-media/agent/conseguira-thegrefg-ganar-a-max-verstap.mp4', media_kind = 'video' where id = 'e0f5b3e9-c908-4291-9cc3-21d9a2505e57' and status = 'open' and media_url is null;
update porras set media_url = 'https://uarnpxjdccbidgzhhavc.supabase.co/storage/v1/object/public/porra-media/agent/quien-ganara-el-derbi-de-madrid-atleti.mp4', media_kind = 'video' where id = '0d0de919-c83a-498c-99c3-d3d22fac107c' and status = 'open' and media_url is null;
update porras set media_url = 'https://uarnpxjdccbidgzhhavc.supabase.co/storage/v1/object/public/porra-media/agent/seguira-nayades-en-la-isla-de-las-tent.mp4', media_kind = 'video' where id = '9c0df0fa-55cf-4ed2-b9de-26cef7a72b3e' and status = 'open' and media_url is null;
update porras set media_url = 'https://uarnpxjdccbidgzhhavc.supabase.co/storage/v1/object/public/porra-media/agent/quien-sera-el-tercer-eliminado-de-maste.mp4', media_kind = 'video' where id = '2a376107-3b52-4fe6-8bf9-dc6f6673c370' and status = 'open' and media_url is null;
update porras set media_url = 'https://uarnpxjdccbidgzhhavc.supabase.co/storage/v1/object/public/porra-media/agent/ganara-marc-marquez-la-carrera-de-motog.mp4', media_kind = 'video' where id = '9d2471de-f9d5-4489-881b-df0893814232' and status = 'open' and media_url is null;
update porras set media_url = 'https://uarnpxjdccbidgzhhavc.supabase.co/storage/v1/object/public/porra-media/agent/ganara-venezuela-a-peru-en-la-final-del.mp4', media_kind = 'video' where id = 'e615cc56-fa03-46ed-b25f-83b584521a63' and status = 'open' and media_url is null;
update porras set media_url = 'https://uarnpxjdccbidgzhhavc.supabase.co/storage/v1/object/public/porra-media/agent/quien-ganara-el-duelo-entre-luzu-y-olga.mp4', media_kind = 'video' where id = '13ef4a2e-2e02-428e-82ae-7e6b65e6cb3b' and status = 'open' and media_url is null;
update porras set media_url = 'https://uarnpxjdccbidgzhhavc.supabase.co/storage/v1/object/public/porra-media/agent/entrara-where-is-gone-de-rosalia-en.mp4', media_kind = 'video' where id = 'baa1ea58-5473-4d3e-a161-a4f156b16cc2' and status = 'open' and media_url is null;
update porras set media_url = 'https://uarnpxjdccbidgzhhavc.supabase.co/storage/v1/object/public/porra-media/agent/sera-albert-barranco-el-proximo-expulsa.mp4', media_kind = 'video' where id = '6a638fa4-74c1-4845-932c-43bc33e41c5c' and status = 'open' and media_url is null;
update porras set media_url = 'https://uarnpxjdccbidgzhhavc.supabase.co/storage/v1/object/public/porra-media/agent/cual-de-los-hermanos-thompson-firmara-p.mp4', media_kind = 'video' where id = '1ca2801c-0aed-448e-9184-77b82584e07b' and status = 'open' and media_url is null;
update porras set media_url = 'https://uarnpxjdccbidgzhhavc.supabase.co/storage/v1/object/public/porra-media/agent/participara-espana-en-eurovision-2027.mp4', media_kind = 'video' where id = 'def91954-2e35-46df-903c-2cefdff316b1' and status = 'open' and media_url is null;
update porras set media_url = 'https://uarnpxjdccbidgzhhavc.supabase.co/storage/v1/object/public/porra-media/agent/se-celebrara-la-velada-del-ano-vi-de-ib.mp4', media_kind = 'video' where id = '9d936790-31d9-438b-846a-4e6234c01989' and status = 'open' and media_url is null;
update porras set media_url = 'https://uarnpxjdccbidgzhhavc.supabase.co/storage/v1/object/public/porra-media/agent/quien-ganara-mas-premios-latin-grammy-2.mp4', media_kind = 'video' where id = '2eee55ad-c406-4aec-9cc1-488a0b5c7b2c' and status = 'open' and media_url is null;
update porras set media_url = 'https://uarnpxjdccbidgzhhavc.supabase.co/storage/v1/object/public/porra-media/agent/conseguira-movistar-koi-clasificarse-pa.mp4', media_kind = 'video' where id = 'fb481081-6aba-4101-9fda-407e1cb775a1' and status = 'open' and media_url is null;
update porras set media_url = 'https://uarnpxjdccbidgzhhavc.supabase.co/storage/v1/object/public/porra-media/agent/completara-la-kings-league-mena-en-riad.mp4', media_kind = 'video' where id = '9799f704-e1ae-4a6f-bd00-e21d5ba022f7' and status = 'open' and media_url is null;
update porras set media_url = 'https://uarnpxjdccbidgzhhavc.supabase.co/storage/v1/object/public/porra-media/agent/seguira-carlos-alcaraz-los-consejos-de.mp4', media_kind = 'video' where id = '263f914b-53f8-461b-8bbb-1140611eb998' and status = 'open' and media_url is null;
